---
# group_vars/local.yml
# These variables apply to the LOCAL environment (your Vagrant machine).

# 'project_name' and 'base_domain' will be used to create a hosts entry for exampleproject.base_domain
# i.e. exampleproject.local
project_name: exampleproject
base_domain: local

# You will USUALLY not need to modify the vhost variables as long as the variables above are set.
vhost:
  project_name: "{{ project_name }}"
  domain: "{{ project_name }}.{{ base_domain }}"
  document_root: "{{ apache_vhosts_base_dir }}/vhosts/{{ project_name }}.{{ base_domain }}/public_html"
  log_root: "{{ apache_vhosts_base_dir }}/vhosts/{{ project_name }}.{{ base_domain }}/logs"
  config_filename: "{{ project_name }}.{{ base_domain }}.conf"
  owner: "vagrant"
  group: "vagrant"
